José Luis Yépez García - Ejercicios Tema 2: Cinema, Filtros
UnirCs/DWFS-PER11090-2425 pull request #106
Opened 2024-11-15 19:05 UTC by joseluis-dev

2024-11-16 13:57 UTC, UnirCs commented on Tema_2/Jose_Luis_Yepez_Garcia/Cinema/butacas.js
> +        return seatsSet;
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa.

2024-11-16 13:57 UTC, UnirCs requested changes
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa.

2024-11-16 18:30 UTC, joseluis-dev commented
He procedido a corregir el código de acuerdo a sus observaciones profe, quedo atento por cualquier retroalimentación.

2024-11-17 01:00 UTC, UnirCs approved these changes
OK!

2024-11-17 01:01 UTC, merged