Envio solución ejercicio Cinema y Filtros-Tema2
UnirCs/DWFS-PER11090-2425 pull request #108
Opened 2024-11-16 02:00 UTC by Jhon-Salguero

Envio solución ejercicio Cinema y Filtros-Tema2

2024-11-16 13:58 UTC, UnirCs commented on Tema_2/Jhon_Edisson_Salguero_Pinzon/Cinema/cinema.js
> +                return new Set(asientosDisponibles);
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa.

2024-11-16 13:58 UTC, UnirCs requested changes
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa.

2024-11-20 23:41 UTC, UnirCs requested changes
No se ha eliminado el return dentro del bucle

2024-11-21 00:09 UTC, Jhon-Salguero commented
Envio correcciones de los ejercicios.

2024-11-21 19:41 UTC, merged