Unir Tema2 Jhon Roberth Fernandez
UnirCs/DWFS-PER11090-2425 pull request #109
Opened 2024-11-16 04:59 UTC by JhonRoberthUnir

Master en desarrollo de software y sistemas informaticos. 
Desarrollo web fullstack
Tema2

2024-11-16 13:59 UTC, UnirCs commented on Tema_2/Jhon_Roberth_Fernandez_Ortiz/cinema/cinema.js
> +                break;
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa, además en este caso se nota que no se ha analizado algorítmicamente el problema

2024-11-16 13:59 UTC, UnirCs requested changes
Como comenté en clase no está permitido usar breaks, continues o returns dentro de bucles ya que hacen que no se cumplan las invariantes del programa, además en este caso se nota que no se ha analizado algorítmicamente el problema

2024-11-17 00:37 UTC, JhonRoberthUnir commented on Tema_2/Jhon_Roberth_Fernandez_Ortiz/cinema/cinema.js
> +                break;
Saludos, elimine los break y return dentro de los bucles y probe la funcionalidad. 
No entiendo la parte de que no se a analizado algoritmicamete el problema?

2024-11-17 01:01 UTC, UnirCs commented on Tema_2/Jhon_Roberth_Fernandez_Ortiz/cinema/cinema.js
> +                break;
Me refiero a que la función es innecesariamente compleja

2024-11-17 01:01 UTC, UnirCs approved these changes
OK!

2024-11-17 01:02 UTC, merged