Tarea 2
UnirCs/DWFS-PER11090-2425 pull request #149
Opened 2024-11-18 05:37 UTC by RaulCastro1000

Buenas noches profesor envío tarea 2. De igual forma a pesar que he encontrado/leido/practicado varios recursos en internet, manuales, apps de JS, entre otros, si me ha sido difícil. Agradecería si adicional a estos ejercicios podría brindarme algunos links que tal vez tenga con ejercicios o ruta de aprendizaje para tratar de seguir practicando.

Gracias,

2024-11-18 23:20 UTC, UnirCs commented on Tema_2/Raul_Castro_Cepulo/Cinema/cinema.js
> +                    return; // Terminamos esta iteración del forEach
es necesario refactorizar para que el bucle termine por si solo, no forzandolo. te recomiendo revisar mi solucion en el foro, esta que propones es algo ineficiente, hay muchas casuisticas que no se ejecutan

2024-11-18 23:20 UTC, UnirCs requested changes
Es necesario refactorizar para no violar invariantes (no usar breaks, continues o return dentro de bucles)

2024-11-18 23:22 UTC, UnirCs commented
Raúl, te dejo por aqui 5 ejercicios más. Está incluida la solución que yo doy (no la mires ;) ) y un ejemplo de lo que debería hacer:

### Ejercicio 1: Encontrar el Segundo Número Más Grande en un array
**Problema:** Escribe una función que tome un array de números y devuelva el segundo número más grande.

**Solución:**
```javascript
function segundoMasGrande(arr) {
  if (arr.length < 2) return null;
  let primero = -Infinity, segundo = -Infinity;
  for (let num of arr) {
    if (num > primero) {
      segundo = primero;
      primero = num;
    } else if (num > segundo && num < primero) {
      segundo = num;
    }
  }
  return segundo;
}

// Ejemplo de uso:
console.log(segundoMasGrande([10, 5, 8, 12, 7])); // Salida: 10
```
**Explicación:** La función itera a través del array, actualizando los números primero y segundo más grandes según corresponda.

### Ejercicio 2: Eliminar Duplicados de un array
**Problema:** Escribe una función que elimine elementos duplicados de un array.

**Solución:**
```javascript
function eliminarDuplicados(arr) {
  return [...new Set(arr)];
}

// Ejemplo de uso:
console.log(eliminarDuplicados([1, 2, 2, 3, 4, 4, 5])); // Salida: [1, 2, 3, 4, 5]
```
**Explicación:** La función usa un `Set` para filtrar automáticamente los duplicados y luego lo convierte de nuevo en un array.

### Ejercicio 3: Rotar un array
**Problema:** Escribe una función que rote un array a la derecha por un número dado de pasos.

**Solución:**
```javascript
function rotararray(arr, pasos) {
  pasos = pasos % arr.length;
  return arr.slice(-pasos).concat(arr.slice(0, -pasos));
}

// Ejemplo de uso:
console.log(rotararray([1, 2, 3, 4, 5], 2)); // Salida: [4, 5, 1, 2, 3]
```
**Explicación:** La función divide el array en dos partes y las concatena en el orden rotado.

### Ejercicio 4: Encontrar la Intersección de Dos arrays
**Problema:** Escribe una función que encuentre la intersección de dos arrays.

**Solución:**
```javascript
function interseccionarrays(arr1, arr2) {
  return arr1.filter(value => arr2.includes(value));
}

// Ejemplo de uso:
console.log(interseccionarrays([1, 2, 3, 4], [3, 4, 5, 6])); // Salida: [3, 4]
```
**Explicación:** La función filtra elementos del primer array que también están presentes en el segundo array.

### Ejercicio 5: Aplanar un array Anidado
**Problema:** Escribe una función que aplane un array anidado.

**Solución:**
```javascript
function aplanararray(arr) {
  return arr.reduce((plano, aAplanar) => {
    return plano.concat(Array.isArray(aAplanar) ? aplanararray(aAplanar) : aAplanar);
  }, []);
}

// Ejemplo de uso:
console.log(aplanararray([1, [2, [3, 4], 5], 6])); // Salida: [1, 2, 3, 4, 5, 6]
```
**Explicación:** La función usa recursión y `reduce` para aplanar arrays anidados en un solo array.

2024-11-19 02:03 UTC, RaulCastro1000 commented
Lo màximo profe muchas gracias!

2024-12-08 20:12 UTC, UnirCs commented
Se cierra PR por inactividad

2024-12-08 20:12 UTC, closed without merging