Ejercicios completos tema 2
UnirCs/DWFS-PER11090-2425 pull request #152
Opened 2024-11-18 16:15 UTC by Xavi2996

Saludos cordiales,
Adjunto los ejercicios terminados del tema 2

2024-11-18 23:26 UTC, UnirCs commented on Tema_2/Angel_Xavier_Cobos_Andrango/cinema/actividad.js
> +        return mySet
como comenté en clase no se aceptan soluciones con breaks, returns o continues dentro de bucles ya que se violan las invariantes de los mismos.

2024-11-18 23:27 UTC, UnirCs requested changes
como comenté en clase no se aceptan soluciones con breaks, returns o continues dentro de bucles ya que se violan las invariantes de los mismos.
Por otro lado revisa la logica del programa, es innecesariamente compleja.

2024-11-20 23:39 UTC, Xavi2996 commented
Saludos cordiales,
El problema de returns fue solventado. Gracias por el comentario

2024-11-20 23:40 UTC, UnirCs reviewed
OK, aunque no entiendo por que comentaste la creacion de la matriz de butacas, lo has probado?? Este codigo no funcionaria si lo ejecuto :O

2024-11-20 23:41 UTC, UnirCs requested changes
Pdte confirmar por que se comenta el codigo

2024-11-20 23:45 UTC, Xavi2996 commented
Saludos,
Fue un descuido el enviar comentado. Lo probe con matriz externa por facilidad de pruebas sin embargo ducniona para cualquier tipo de matriz. me mantengo atento a los comentarios

2024-11-21 19:41 UTC, UnirCs approved these changes
OK!

2024-11-21 19:42 UTC, merged