Ejercicios numero 1 y 2 - Tema 2
UnirCs/DWFS-PER11090-2425 pull request #158
Opened 2024-11-18 23:07 UTC by miguelangel6969

2024-11-18 23:36 UTC, UnirCs commented on Tema_2/Miguel_Angel_Hernandez_Munoz/Cinema/cinema.js
> +            return;
como comentaba en clase, no se aceptan soluciones que violen invariantes de bucles al usar breaks, return o continues dentro de ellos.

2024-11-18 23:37 UTC, UnirCs commented on Tema_2/Miguel_Angel_Hernandez_Munoz/Cinema/cinema.js
> +                return {
como comentaba en clase, no se aceptan soluciones que violen invariantes de bucles al usar breaks, return o continues dentro de ellos.

2024-11-18 23:37 UTC, UnirCs requested changes
como comentaba en clase, no se aceptan soluciones que violen invariantes de bucles al usar breaks, return o continues dentro de ellos.

2024-11-19 00:10 UTC, miguelangel6969 commented on Tema_2/Miguel_Angel_Hernandez_Munoz/Cinema/cinema.js
> +            return;
Se realizaron las modificaciones solicitadas

2024-11-19 00:10 UTC, miguelangel6969 commented on Tema_2/Miguel_Angel_Hernandez_Munoz/Cinema/cinema.js
> +                return {
Se realizaron las modificaciones solicitadas

2024-11-19 08:50 UTC, UnirCs approved these changes
OK!

2024-11-19 08:50 UTC, merged