Ejercicios Tema 1
UnirCs/DWFS-PER11090-2425 pull request #160
Opened 2024-11-19 00:53 UTC by Denniss2C

Se realizó los ejercicios del tema 1 para seguir con el tema 2

2024-11-19 00:54 UTC, Denniss2C commented
Revisar para el pull

2024-11-19 08:51 UTC, UnirCs commented on Tema_1/Dennis_Sebastian_Caisa_Llano/CINE/index.html
> +    <style>
No debe haber estilos inline

2024-11-19 08:52 UTC, UnirCs requested changes
No debe haber estilos inline

2024-11-26 09:01 UTC, UnirCs commented
PR Cerrada por inactividad

2024-11-26 09:01 UTC, closed without merging