Ejercicios Tema 3 + Corrección ejercicio tema 2
UnirCs/DWFS-PER11090-2425 pull request #167
Opened 2024-11-19 15:31 UTC by jorgeromeral

2024-11-19 23:18 UTC, UnirCs commented on Tema_2/Jorge_Romeral_Morales/02_Cine/script.js
> +                    return (asientosLibres) // Devolver los asientos
como comente en clase no se aceptan soluciones que violen invariantes de bucles usando breaks, continues o returns dentro de bucles.

2024-11-19 23:18 UTC, UnirCs commented on Tema_3/Jorge_Romeral_Morales/02_Cine/script.js
> +                    return console.log(`Se encontraron ${reserva} asientos consecutivos:`,asientosLibres) // Devolver los asientos
como comente en clase no se aceptan soluciones que violen invariantes de bucles usando breaks, continues o returns dentro de bucles.

2024-11-19 23:18 UTC, UnirCs requested changes
como comente en clase no se aceptan soluciones que violen invariantes de bucles usando breaks, continues o returns dentro de bucles.

2024-11-25 12:52 UTC, jorgeromeral commented
Cambios corregidos, pendiente de aprobación

2024-11-26 09:05 UTC, UnirCs approved these changes
OK!

2024-11-26 09:05 UTC, merged