Cinema
UnirCs/DWFS-PER11090-2425 pull request #176
Opened 2024-11-20 03:54 UTC by camilorafaelcardenas

2024-11-20 04:01 UTC, camilorafaelcardenas commented
Ejercicio de Cinema

2024-11-20 04:04 UTC, camilorafaelcardenas commented
Cinwma

2024-11-24 23:45 UTC, camilorafaelcardenas commented
Ejercicios Tema 2

2024-11-26 08:38 UTC, UnirCs requested changes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-12-02 02:44 UTC, camilorafaelcardenas reviewed
Ejercicios Tema 3

2024-12-02 02:48 UTC, camilorafaelcardenas commented on Tema_3/Camilo_Rafael_Cardenas_Rodriguez/Chuck/index.html
API Chuck Norris

2024-12-03 03:27 UTC, camilorafaelcardenas commented
Tema 4 Camilo Cardenas

2024-12-08 12:20 UTC, UnirCs requested changes
Se siguen violando invariantes en la funcion suggest, no puede haber breaks, returns o continues dentro de bucles.

2024-12-12 22:52 UTC, UnirCs commented
No prestes atención a los errores de Sonar Cloud, ha sido una prueba.

2024-12-15 10:57 UTC, UnirCs commented
PR cerrada por inactividad. Reábrela de nuevo cuando tengas tiempo o incluyas otras actividades :)

2024-12-15 10:57 UTC, closed without merging