Ejercicio tema 2 JavaScript
UnirCs/DWFS-PER11090-2425 pull request #178
Opened 2024-11-20 08:08 UTC by joseferms

Buen día profe envio ejercicios de tema 2

2024-11-20 23:33 UTC, UnirCs commented on Tema_2/Jose_Fernando_Martinez/cinema/cinema.js
> +                      return new Set([]) ;
como comentaba en clase, no se aceptan soluciones que violen invariantes de bucles al usar breaks, return o continues dentro de ellos.

2024-11-20 23:33 UTC, UnirCs requested changes
como comentaba en clase, no se aceptan soluciones que violen invariantes de bucles al usar breaks, return o continues dentro de ellos.

2024-11-21 18:26 UTC, joseferms commented
OK profe, pensé que solo eran breaks, pero siendo tambien returns y continues invariantes, lo corrijo, gracias profe

2024-11-21 19:42 UTC, UnirCs requested changes
Se modifican archivos de varias personas, es necesario sincronizar el fork para que solo se muestren tus cambios

2024-11-22 00:57 UTC, closed without merging