Corrección Tema 1
UnirCs/DWFS-PER11090-2425 pull request #180
Opened 2024-11-20 13:37 UTC by YuslyArboleda

2024-11-20 23:35 UTC, UnirCs commented on .vscode/settings.json
Este archivo no se encuentra dentro de tu carpeta

2024-11-20 23:35 UTC, UnirCs requested changes
Debes eliminar los archivos que estén fuera de tu carpeta

2024-11-21 20:44 UTC, YuslyArboleda commented
Archivo eliminado

2024-11-23 00:20 UTC, UnirCs approved these changes
OK! ahora si

2024-11-23 00:21 UTC, merged