implementacion ejercios tema 2
UnirCs/DWFS-PER11090-2425 pull request #212
Opened 2024-11-24 04:37 UTC by Ingetronika

funciones para tratamiento de imágenes implementadas
función para selección de butacas disponibles implementada

2024-11-26 08:42 UTC, UnirCs requested changes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 17:33 UTC, Ingetronika commented on Tema_2/hugo_tovio_barreto/cinema.js
> +                    return new Set(ids); // Devolver un Set con los IDs de los asientos seleccionados
estimado profesor
para solucionar el inconveniente con las sentencias que violan las invariantes en la función **suggest** he implementado una variable de tipo boleana (encontrados =false),con la cual pretendo que se finalice o el ciclo for y devolver el set con los asientos sugeridos   **for (let i = N - 1; i >= 0 && !encontrados; i--)**

2024-11-27 21:56 UTC, UnirCs commented on Tema_3/Readme.md
No puedes eliminar mi archivo!

2024-11-27 21:56 UTC, UnirCs requested changes
Es neceario revertir cambios en mis archivos

2024-12-08 12:21 UTC, UnirCs commented on Tema_5/hugo_tovio_barreto/mi-app
Se ha subido como submodulo de git, hay que subir los archivos de forma normal (sin el .git) para que podamos verlos todos, de otra forma solo puedes verlo tu :(

2024-12-08 12:21 UTC, UnirCs commented on Tema_3/Readme.md
Debes revertir cambios en este fichero que es mío

2024-12-08 12:22 UTC, UnirCs requested changes
OK en cuanto a lo de los invariantes, no obstante hay que solucionar lo que he comentado en las otras secciones

2024-12-08 17:03 UTC, Ingetronika commented on Tema_5/hugo_tovio_barreto/mi-app
buenos días profe

saludos,le agradeceria y usted discúlpeme la confusion,como vera apenas voy en la curva de aprendizaje de Github,le agradeceria si el lunes despues de clase me regalaria 10min para hacer el proceso,
lo que ha sucedido es lo siguiente: yo cree un repositorio nuevo en mi cuenta de github,donde puse mi aplicación en react del cine independientemente del repositorio suyo,una vez desplegué la aplicacion,lo que hice fue copiar la carpeta de mi aplicación llamada mi-app y me la lleve al repositorio local  forkeado del suyo y dentro del tema5 cree la carpeta con mi nombre y dentro puse la carpeta mi-app,luego lo que hice fue abrí el repositorio en VSC y, pienso que hay empezó la confusión,supuse que como ya había colocado la carpeta directamente en el repositorio local ,solo era hacer un git push origin master para que me apareciera en mi repositorio remoto en github,efectivamente me aparece pero es una carpeta con una flechita dentro diferente al otras que he hecho en las otras actividades y cunado le hago click no abre

2024-12-08 20:04 UTC, UnirCs commented on Tema_5/hugo_tovio_barreto/mi-app
Hola Hugo, el proceso está bien, lo único que no hay que incluir es el .git porque se crean submódulos. Mañana podemos verlo

2024-12-12 22:15 UTC, UnirCs commented on Tema_3/Readme.md
Este archivo se sigue modificando, sustituyelo por el que hay en master y la pr queda perfecta :D

2024-12-12 22:16 UTC, UnirCs requested changes
Necesario revertir 1 archivo

2024-12-15 10:57 UTC, UnirCs commented
PR cerrada por inactividad. Reábrela de nuevo cuando tengas tiempo o incluyas otras actividades :)

2024-12-15 10:57 UTC, closed without merging