Ejercicios tema 2
UnirCs/DWFS-PER11090-2425 pull request #226
Opened 2024-11-25 16:10 UTC by Jefffer

## Activity 2

This pull request includes the solution for Activity 2. There are two JavaScript files, `cinema.js` and `actividad.js`. Below is a summary of the most important changes:

### Cinema Seat Management:
* Introduced a function to initialize a matrix of seats with a specified size and initial state (`setup`).
* Added a function to suggest contiguous seats starting from the row furthest from the screen (`suggest`).

### Image Processing Operations:
* Added functions to convert images to different color scales: red, green, blue, grayscale, and black and white (`redConverter`, `greenConverter`, `blueConverter`, `greyConverter`, `blackAndWhiteConverter`).
* Implemented a function to scale down an image by removing every other row and column (`scaleDown`).
* Added functions to adjust image brightness and invert colors (`dimBrightness`, `invertColors`).
* Introduced a function to merge two images with specified alpha blending factors (`merge`).

These changes enhance the functionality of the cinema seat management system and provide a comprehensive set of image processing tools.

2024-11-26 08:52 UTC, UnirCs commented on Tema_2/Jefferson_Rodriguez_Rodriguez/cinema/cinema.js
> +                    return asientosSugeridos;
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 08:52 UTC, UnirCs requested changes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 10:21 UTC, Jefffer commented on Tema_2/Jefferson_Rodriguez_Rodriguez/cinema/cinema.js
> +                    return asientosSugeridos;
Corregido, me dices si algo no te cuadra :)

2024-11-27 21:57 UTC, UnirCs approved these changes
OK!

2024-11-27 21:57 UTC, merged