feat(Enrique_Teruel_Gutierrez): tema 1, tema 2, tema 3, tema 4
UnirCs/DWFS-PER11090-2425 pull request #230
Opened 2024-11-26 00:33 UTC by enriqueteru

2024-11-26 08:56 UTC, UnirCs commented on Tema_2/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
> +            return consecutiveSeats;
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 08:57 UTC, UnirCs commented on Tema_3/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
> +            return consecutiveSeats;
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 08:57 UTC, UnirCs commented on Tema_4/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
> +            return consecutiveSeats;
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-26 08:58 UTC, UnirCs requested changes
En general está todo bastante bien Enrique, a excepcion del tema de las invariantes

2024-11-26 21:43 UTC, enriqueteru commented on Tema_2/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
> +            return consecutiveSeats;
Hola, mando versión revisada. 

Saludos.

2024-11-27 21:57 UTC, UnirCs approved these changes
OK!

2024-11-27 21:58 UTC, merged