Tema 2. Ejercicios Filtros y Cinema
UnirCs/DWFS-PER11090-2425 pull request #234
Opened 2024-11-26 12:30 UTC by jdtena

2024-11-27 21:59 UTC, UnirCs commented on Tema_2/JoseMaria_DeTena_Rubio/Cinema/cinema.js
> +                    return resultado;
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-27 21:59 UTC, UnirCs requested changes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-28 17:55 UTC, jdtena commented
Hola, Jesús. He actualizado la función suggest() para evitar la violación de invariantes. Pensaba que sólo debíamos evitar break y continue, pero ya he visto los "peligros" de return después de profundizar en ello.

Gracias por las apreciaciones, estoy aprendiendo mucho.

2024-11-30 22:56 UTC, UnirCs approved these changes
OK!

2024-11-30 22:56 UTC, UnirCs commented
Gracias por tus palabras :)!

2024-11-30 22:56 UTC, merged