Actividad #4
UnirCs/DWFS-PER11090-2425 pull request #238
Opened 2024-11-27 04:52 UTC by theddylunaUNIR

Se solucionan los Ejercicios del Tema 4

2024-11-27 22:01 UTC, UnirCs commented on Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/cinema.html
> +            <input type="number" oninput="suggest(this.value)" class="form-control mx-auto"
hay que eliminar referencias a metodos JS en el html

2024-11-27 22:02 UTC, UnirCs requested changes
recuerda añadir funcionalidad al boton desde el script js, no desde el html

2024-11-28 02:40 UTC, theddylunaUNIR commented
Se realizan los cambios solicitados

2024-11-30 22:57 UTC, UnirCs approved these changes
OK!

2024-11-30 22:57 UTC, merged