Ejercicios tema 2
UnirCs/DWFS-PER11090-2425 pull request #247
Opened 2024-11-28 08:52 UTC by missicullera

2024-11-30 23:05 UTC, UnirCs commented on Tema_2/Jose_Maria_Blasco_Roman/Cine/cine.js
> +                    return new Set(ids); // Retornar los IDs si encontramos suficientes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-11-30 23:06 UTC, UnirCs requested changes
como comente en clase, no se aceptan soluciones que violen invariantes usando breaks, return o continue dentro de bucles.

2024-12-03 08:14 UTC, missicullera commented on Tema_2/Jose_Maria_Blasco_Roman/Cine/cine.js
> +                    return new Set(ids); // Retornar los IDs si encontramos suficientes
Disculpa Jesús, ya lo he corregido. Ya me confirmas. Gracias

2024-12-08 12:22 UTC, UnirCs approved these changes
OK!

2024-12-08 12:22 UTC, merged