Tema1 ejercicios freddy ponce
UnirCs/DWFS-PER11090-2425 pull request #261
Opened 2024-11-30 21:46 UTC by fponce99

Tema 1 ejercicio 1
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/110bef87-94fb-49de-9c8f-ea2c25be38e6">

Tema 1 Ejercicio 2
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/7d78a2f7-ee6e-4f1b-8e0e-b5fd801bcf5f">

2024-11-30 23:17 UTC, UnirCs commented on Tema_1/Freddy_Alberto_Ponce_Muzzio/Cinema/index.html
> +        <hr style="border: 3px solid white; width: 50%">
recuerda eliminar estilos inline https://dev.to/alim1496/avoid-using-inline-css-styles-5b6p

2024-11-30 23:17 UTC, UnirCs requested changes
Necesario eliminar estilos inline: https://dev.to/alim1496/avoid-using-inline-css-styles-5b6p

2024-11-30 23:54 UTC, fponce99 commented on Tema_1/Freddy_Alberto_Ponce_Muzzio/Cinema/index.html
> +        <hr style="border: 3px solid white; width: 50%">
resuleto ✅

2024-12-01 20:50 UTC, UnirCs approved these changes
OK!

2024-12-01 20:50 UTC, merged