T234
UnirCs/DWFS-PER11090-2425 pull request #268
Opened 2024-12-01 21:57 UTC by victormanuel08

2024-12-08 12:23 UTC, UnirCs commented on .gitignore
No puedes modificar archivos que no son tuyos

2024-12-08 12:23 UTC, UnirCs commented on Tema_3/Readme.md
No puedes eliminar mis archivos

2024-12-08 12:23 UTC, UnirCs commented on Tema_4/Readme.md
No puedes eliminar mis archivos

2024-12-08 12:23 UTC, UnirCs commented on et --soft HEAD~2
No puedes añadir archivos fuera de tu carpeta

2024-12-08 12:23 UTC, UnirCs commented on et --soft HEAD~2
No puedes añadir archivos fuera de tu carpeta

2024-12-08 12:23 UTC, UnirCs commented on et --soft HEAD~2
No puedes añadir archivos fuera de tu carpeta

2024-12-08 12:24 UTC, UnirCs requested changes
PR con archivos incorrectos

2024-12-08 13:43 UTC, victormanuel08 commented on .gitignore
sinceramente no se como corregir ni como subir los ejercicios

2024-12-08 20:08 UTC, UnirCs commented on .gitignore
Los has subido bien, pero has tocado mis archivos en el proceso. Tienes que sustituir los que ya existían con las versiones que hay en mi repositorio, en master.
Para los archivos que has creado fuera de tus carpetas, eliminarlos.

2024-12-08 20:08 UTC, UnirCs commented
Los has subido bien, pero has tocado mis archivos en el proceso. Tienes que sustituir los que ya existían con las versiones que hay en mi repositorio, en master.
Para los archivos que has creado fuera de tus carpetas, eliminarlos.

2024-12-15 10:56 UTC, UnirCs commented
PR cerrada por inactividad. Reábrela de nuevo cuando tengas tiempo o incluyas otras actividades :)

2024-12-15 10:56 UTC, closed without merging