Ejercicios Marlon Valbuena
UnirCs/DWFS-PER11090-2425 pull request #270
Opened 2024-12-02 01:29 UTC by Programvr

2024-12-08 12:25 UTC, UnirCs commented on Tema_2/Marlon_Arley_Valbuena_Rincon/Cinema/Cinema.js
> +                    return new Set(ids);
como comente en clase, no esta permitido usar breaks, returns o continues dentro de bucles y violar sus invariantes.

2024-12-08 12:25 UTC, UnirCs requested changes
como comente en clase, no esta permitido usar breaks, returns o continues dentro de bucles y violar sus invariantes.

2024-12-09 23:33 UTC, Programvr commented on Tema_2/Marlon_Arley_Valbuena_Rincon/Cinema/Cinema.js
> +                    return new Set(ids);
Realice nuevamente un commit con el respectivo ajuste.

2024-12-10 00:03 UTC, UnirCs commented on Tema_4/Marlon_Arley_Valbuena_Rincon/Cinema/eleccion_asientos/index.html
> +      <input type="number" id="seatsToReserve" class="form-control w-25 mx-auto" placeholder="Ej: 2" oninput="suggest(butacas,this.value)">
recuerda que a partir de ahora que usamos DOM, no tenemos codigo JS en archivos HTML, esa asignacion de logica ocurre en archivo JS mediante query selector o selectores

2024-12-10 00:03 UTC, UnirCs requested changes
Necesario eliminar logica JS de archivos html

2024-12-13 22:49 UTC, Programvr commented on Tema_4/Marlon_Arley_Valbuena_Rincon/Cinema/eleccion_asientos/index.html
> +      <input type="number" id="seatsToReserve" class="form-control w-25 mx-auto" placeholder="Ej: 2" oninput="suggest(butacas,this.value)">
Ajuste solicitado en el pull requests

2024-12-15 10:51 UTC, UnirCs approved these changes
OK!

2024-12-15 10:51 UTC, merged