Tarea 4
UnirCs/DWFS-PER11090-2425 pull request #275
Opened 2024-12-02 13:56 UTC by rfalcon97

Tarea 4

2024-12-08 12:28 UTC, UnirCs commented on Tema_4/Ricardo_David_Falcon_Falcon/cinema/index.html
> +                <input type="number" id="numAsientos" name="numAsientos" min="1" max="10" step="1" oninput="sugerir(this.value)">
recuerda que eliminamos del html cualquier referencia a codigo js de ahora en adelante

2024-12-08 12:28 UTC, UnirCs requested changes
Es necesario eliminar llamadas a metodos js en html

2024-12-09 14:39 UTC, rfalcon97 commented
Se realizó los cambios solicitados. Se eliminó llamadas a metodos js en html

2024-12-10 00:03 UTC, UnirCs approved these changes
OK!

2024-12-10 00:03 UTC, merged