Add Tema_2, Tema_3 and Tema_4 files
UnirCs/DWFS-PER11090-2425 pull request #283
Opened 2024-12-03 05:56 UTC by MarcosKlender

With this PR I'm up to date to continue with React task! 🗿

2024-12-08 12:39 UTC, UnirCs commented on Tema_4/Marcos_Klender_Carrasco_Gonzaga/CINEMA/index.html
> +                <input type="number" oninput="updateSelection()" name="number" id="inputNumber" required>
recuerda que si trabajamos con dom desde otro archivo js no tiene sentido meter aqui esos onInput y no estamos separando funcionalidades!

2024-12-08 12:40 UTC, UnirCs requested changes
Muy bien en general todo, solo quita ese onInput en el html y genial!

2024-12-09 16:00 UTC, MarcosKlender commented on Tema_4/Marcos_Klender_Carrasco_Gonzaga/CINEMA/index.html
> +                <input type="number" oninput="updateSelection()" name="number" id="inputNumber" required>
Acabo de hacer un commit con esa correción, ¡gracias por el feedback!

2024-12-09 16:05 UTC, MarcosKlender commented
> Muy bien en general todo, solo quita ese onInput en el html y genial!

Acabo de corregirlo en el último commit, ¡gracias! 🚀

2024-12-10 00:04 UTC, UnirCs approved these changes
OK!

2024-12-10 00:04 UTC, merged