Cambios Tema3
UnirCs/DWFS-PER11090-2425 pull request #332
Opened 2024-12-22 02:01 UTC by Jhon-Salguero

Cambios/Solucion Tema3.

2024-12-22 02:27 UTC, Jhon-Salguero commented
Cambios Cinema Chistes Tema3

2024-12-22 20:49 UTC, UnirCs commented on Tema_3/.vscode/launch.json
No puedes incluir archivos fuera de tu carpeta

2024-12-22 20:50 UTC, UnirCs requested changes
PR Incorrecta, incluyes archivos fuera de tu carpeta

2024-12-26 16:42 UTC, UnirCs commented on Tema_3/.vscode/launch.json
Se mantiene el archivo, por favor eliminalo

2024-12-26 16:42 UTC, UnirCs requested changes
Archivos incorrectos siguen estando

2024-12-28 02:31 UTC, Jhon-Salguero commented
Buenas noches Ingeniero no entiendo cuales son los archivos a los cuales hace referencia que estan fuera de mi carpeta adjunto captura de pantalla del contenido de mi carpeta:
![Captura](https://github.com/user-attachments/assets/a4055fed-07f1-43fa-ad0a-a8bc2cc71f24)

espero pronta respuesta para hacer la corrección y poder completar el envio de la actividad.

2024-12-29 20:31 UTC, Jhon-Salguero commented
Envio Actividad del tema4 con sus correciones.

2024-12-29 21:08 UTC, Jhon-Salguero commented
Envio solucion tema5.

2025-01-02 23:37 UTC, UnirCs requested changes
La PR modifica archivos de otros estudiantes, es incorrecta

2025-01-02 23:38 UTC, UnirCs commented
Si haces click en el diff, en los archivos que modificas en esta PR, veras que estas tocando archivos de otros compañeros en el tema 5 con algo que hayas hecho a traves del IDE

2025-01-09 03:19 UTC, Jhon-Salguero commented
Buenas noche Ingeniero volví a cargar mis actividades por consola sin utilizar el IDE.

2025-01-09 03:30 UTC, closed without merging

2025-01-09 03:30 UTC, Jhon-Salguero commented
.