avances a hoy
UnirCs/DWFS-PER11090-2425 pull request #345
Opened 2024-12-24 19:49 UTC by sluguera

se adjunta los talleres del 2 hasta el 6

2024-12-24 19:49 UTC, sluguera commented
avances a hoy

2024-12-24 19:50 UTC, sluguera commented
avances a hoy

2024-12-26 16:46 UTC, UnirCs commented on package-lock.json
Archivo en ubicacion incorrecta, no esta en tu carpeta

2024-12-26 16:46 UTC, UnirCs commented on package.json
Archivo en ubicacion incorrecta, no esta en tu carpeta

2024-12-26 16:46 UTC, UnirCs commented on WebApp-Paper-tales/vite.config.js
Este proyecto no forma parte de estos ejercicios, no debe estar aqui

2024-12-26 16:47 UTC, UnirCs commented on Tema_2/Jhonny Sluguer Arana Zambrano/cinema/js/index.js
> +                return new Set(asientosSeleccionados);
como he comentado varias veces, no se admite violar invariantes de bucles usando breaks, returns o continues dentro de bucles

2024-12-26 16:47 UTC, UnirCs commented on Tema_3/Jhonny Sluguer Arana Zambrano/ejercicio2/js/cinema.js
> +                return asientosSeleccionados;
como he comentado varias veces, no se admite violar invariantes de bucles usando breaks, returns o continues dentro de bucles

2024-12-26 16:47 UTC, UnirCs commented on Tema_4/Jhonny Sluguer Arana Zambrano/ejercicio1/js/cinema.js
> +                return asientosSeleccionados;
como he comentado varias veces, no se admite violar invariantes de bucles usando breaks, returns o continues dentro de bucles

2024-12-26 16:48 UTC, UnirCs commented on Tema_4/Jhonny Sluguer Arana Zambrano/ejercicio1/index.html
> +        <input type="number" id="numAsientos" min="1" max="10" placeholder="1-10" class="form-control d-inline-block w-25" onInput="handleInputChange()">
dado que en este ejercicio se separa html + css + js no debe haber referencias aun metodo js en el html

2024-12-26 16:48 UTC, UnirCs commented on Tema_5/Jhonny Sluguer Arana Zambrano/cine-react/README.md
Salvo error falta enlace de vercel en esta tarea

2024-12-26 16:50 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/ejercicio1/calculadora/src/main/java/com/unir/calculadora/CalculadoraApplication.java
En el tema 6 no se pide implementar nada con Java. Se pide un archivo MD con el diseño. Además, los endpoints de la API no están correctamente diseñados. Te recomiendo revisar la sesion de clase con todas las consideraciones que allí se indican.

2024-12-26 16:50 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/ejercicio2/cine/.gitattributes
En el tema 6 no se pide implementar nada con Java. Se pide un archivo MD con el diseño.

2024-12-26 16:51 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/ejercicio3/hundirFlota/.gitattributes
En el tema 6 no se pide implementar nada con Java. Se pide un archivo MD con el diseño.

2024-12-26 16:51 UTC, UnirCs requested changes
Hola Jhonny, creo que tienes que leer más detalladamente los enunciados y revisar de nuevo las sesiones de clase.

2024-12-29 21:58 UTC, sluguera commented
últimos ajustes

2024-12-29 21:59 UTC, sluguera commented
últimos ajustes

2025-01-02 23:33 UTC, UnirCs commented on package-lock.json
Debe eliminarse este archivo que no esta bajo tus carpetas

2025-01-02 23:33 UTC, UnirCs commented on package.json
Debe eliminarse este archivo que no esta bajo tus carpetas

2025-01-02 23:33 UTC, UnirCs commented on Tema_2/Jhonny Sluguer Arana Zambrano/cinema/js/index.js
> +                return new Set(asientosSeleccionados);
No está cambiado

2025-01-02 23:35 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/Calculadora/# API REST de Calculadora Online.md
Los recursos siempre van en plural. "Sumas", "restas"... por otro lado, en las apis no existe la herencia. No puedes crear "sumas" y luego buscar "operaciones". Si tienes post para sumas, restas... tienes que tener get para sumas y restas. si tienes post para operaciones, get para operaciones.

2025-01-02 23:35 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/Cine/# API REST - Sistema de Reserva de.md
Faltan operaciones por implementar

2025-01-02 23:35 UTC, UnirCs commented on Tema_6/Jhonny Sluguer Arana Zambrano/HundirFlota/# API REST - Hundir la Flota.md
Faltan muchas operaciones por implementar

2025-01-02 23:35 UTC, UnirCs requested changes
Se adjuntan comentarios para revisar

2025-01-13 08:54 UTC, closed without merging