Actividad 1 taller cv y cinema
UnirCs/DWFS-PER11090-2425 pull request #348
Opened 2024-12-27 03:34 UTC by axbmunoz

2024-12-27 23:28 UTC, axbmunoz commented
envio de actividad cinema tema 3

2024-12-27 23:48 UTC, UnirCs commented on Tema_2/Alexandra_Bedoya_Muñoz/cinema/script.js
> +                    return new Set(
como he comentado varias veces, no está permitido usar break, continue o return dentro de bucles porque viola sus invariantes

2024-12-27 23:48 UTC, UnirCs requested changes
como he comentado varias veces, no está permitido usar break, continue o return dentro de bucles porque viola sus invariantes

2024-12-28 02:17 UTC, axbmunoz commented on Tema_2/Alexandra_Bedoya_Muñoz/cinema/script.js
> +                    return new Set(
Ya corrijo y lo cargo nuevamente

2025-01-02 23:29 UTC, UnirCs commented on Tema_3/Alexandra_Bedoya_Muñoz/cinema/script.js
> +                    return new Set(
se sigue usando return dentro de bucles

2025-01-02 23:29 UTC, UnirCs requested changes
se sigue usando return dentro de bucles

2025-01-06 17:48 UTC, axbmunoz commented
Ya realice las correcciones

2025-01-08 08:21 UTC, merged