de Israel Alarcon
UnirCs/DWFS-PER11090-2425 pull request #45
Opened 2024-11-10 02:17 UTC by ialarconc

2024-11-10 02:22 UTC, ialarconc commented
saludos

2024-11-10 02:31 UTC, ialarconc commented
Disculpe si hago muchos cambios es que soy nuevo en esto de Git, saludos

2024-11-11 16:21 UTC, UnirCs commented on Tema_1/Juan_Sebastian_Tellez_Montes/CV/index.html
No puedes eliminar el archivo de otra persona

2024-11-11 16:22 UTC, UnirCs requested changes
Debes revertir cambios en los archivos de otros alumnos

2024-11-12 08:31 UTC, UnirCs requested changes
Hola Israel, como puedes ver en el diff se siguen modificando archivos de otras personas

2024-11-13 00:34 UTC, UnirCs requested changes
Los archivos siguen siendo modifcados Israel. Te recomiendo insertarlos manualmente como estaban o crear un nuevo fork.

2024-11-15 00:11 UTC, UnirCs requested changes
Los archivos se siguen modificando. Si no sabes restaurarlos te recomiendo crear un nuevo fork y poner ahí tus archivos. Ten cuidado de ahora en adelante de no tocar otros archivos que no sean tuyos.

2024-11-15 03:57 UTC, closed without merging

2024-11-16 17:33 UTC, ialarconc commented
Estimado Jeses, favor verificar si se subieron los archivos de la tarea1, realice un nuevo fork y subi mis archivos sin tocar ninguna otra carpeta