No puedo hacer pull request
UnirCs/DWFS-PER11090-2425 pull request #50
Opened 2024-11-10 05:41 UTC by RaulCastro1000

Envío de forma manual, no puedo hacer pull request me dice un error de "merge"

2024-11-11 16:25 UTC, UnirCs commented on Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 2/index.html
> +                    <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="Cantidad butacas" style="width: 220px">
Debes eliminar este estilo inline

2024-11-11 16:26 UTC, UnirCs requested changes
Debes eliminar los estilos inline. La pr esta bien hecha. El error que indicas es porque yo tengo que aprobar la pr antes de poder ser mergeada, tal como se indica en la interfaz de github.

2024-11-11 17:29 UTC, RaulCastro1000 commented
Hola profesor, está bien lo reviso, estoy tratando de cerrar unas cosas para estar en la clase.

Sobre el PR era otro tipo de error que justamente no dejaba que subiera a mi GitHub decía algo que tenia "13 commits todavía pendientes" y tenia que eliminarlos primero o revisar col izquierda/derecha.

Por eso tuve que hacer la carga manual a mi Git y luego ya el PR.

Muchas gracias,

2024-11-12 08:32 UTC, UnirCs approved these changes
OK!

2024-11-12 08:32 UTC, merged