PR: se suben actividades tema_2
UnirCs/DWFS-PER11090-2425 pull request #64
Opened 2024-11-12 00:26 UTC by tna3ds

cinema
filtros

2024-11-12 08:16 UTC, UnirCs commented on Tema_2/Fanor_Hernan_Quintero_Atara/cinema/cinema.js
> +                        return new Set(availableSeats);
Viola la invariante del bucle, como comenté no se puede forzar la salida de un bucle de una forma distinta a lo que indique su condición de parada: `j < this.size`

2024-11-12 08:16 UTC, UnirCs requested changes
Es necesario refactorizar para no violar la invariante:
Viola la invariante del bucle, como comenté no se puede forzar la salida de un bucle de una forma distinta a lo que indique su condición de parada: `j < this.size`

2024-11-12 18:19 UTC, tna3ds commented on Tema_2/Fanor_Hernan_Quintero_Atara/cinema/cinema.js
> +                        return new Set(availableSeats);
Se ajusta codigo, de acuerdo a lo comentado

2024-11-13 00:34 UTC, UnirCs approved these changes
OK!

2024-11-13 00:34 UTC, merged