Ejercicios 1 y 2 del tema 1
UnirCs/DWFS-PER11090-2425 pull request #76
Opened 2024-11-12 16:49 UTC by gecamara

Buenas, al crear la carpeta del ejercicio 2, se me creó un fichero .git dentro y se ha subido como subproyecto. He eliminado el fichero .git (después de hacer el push dado que antes no me di cuenta) y he subido las carpetas con los archivos correctos, solo que también se han subido los subproyectos creados por error. Esas carpetas puedes obviarlas.

2024-11-13 00:39 UTC, UnirCs requested changes
Hola German, no puedo obviarlas porque no aparecen los ejercicios al mostrarse como submodulos, reabre la PR para que quede bien por favor.
Lo del tema 1 genial :)

2024-11-14 17:07 UTC, gecamara commented
Hola, el ejercicio 2 del tema 1 se ha subido correctamente, simplemente se han subido más archivos de los que quería. No entiendo a qué te refieres con lo de "reabre la PR para que quede bien".

2024-11-14 17:48 UTC, UnirCs requested changes
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/ad255567-5696-4d72-baaf-f878402f40b6">
Hola German, como puedes ver no está bien subido. Aparecen como submodulos los del tema 2, tienen que aparecer como los del tema 1. Te recomiendo borrar el contenido y subir los archivos sin meter el proyecto git entero, es por eso por lo que detecta submodulos

2024-11-14 18:17 UTC, gecamara commented
Buenas, acabo de eliminar mis carpetas del directorio en local, he hecho push y luego he vuelto a poner mis carpetas, esta vez sin submódulos, para la revisión. Me han salido cambios en 129 ficheros, no sé si son los de mis compañeros y me los marca a mí como cambios, siempre me ha costado entender esta parte, pero creo que ahora estaría todo bien

2024-11-18 18:38 UTC, gecamara commented
Buenas, ya subí los cambios solicitados, pero la pull request sigue etiquetada como fallida, ¿falta algo?

2024-11-18 23:25 UTC, UnirCs approved these changes
Ahora esta todo correcto!

2024-11-18 23:26 UTC, merged