Ejercicios de Tema 2
UnirCs/DWFS-PER11090-2425 pull request #89
Opened 2024-11-13 14:22 UTC by maibarra0904

2024-11-13 20:55 UTC, UnirCs commented on Tema_2/Mario_Alberto_Ibarra_Martinez/Cinema/seatingSuggestion.js
> +                    return asientos;
como comenté en clase, no se puede violar la invariante de los bucles. No se puede usar continue, return o break dentro de bucles. El bucle debe terminar por si solo.
Violas la condición del bucle `for (let j = 0; j < N; j++)`

2024-11-13 20:55 UTC, UnirCs requested changes
Necesario fix para no violar invariante

2024-11-13 23:44 UTC, maibarra0904 commented on Tema_2/Mario_Alberto_Ibarra_Martinez/Cinema/seatingSuggestion.js
> +                    return asientos;
Saludos, el return está fuera del bucle, no dentro, favor me confirma, gracias.

2024-11-14 17:51 UTC, UnirCs commented on Tema_2/Mario_Alberto_Ibarra_Martinez/Cinema/seatingSuggestion.js
> +                    return asientos;
Hola Mario.
Leyendo tu codigo, veo que está dentro del bucle, solo que bastante lejos, me refiero al bucle principal.

```java
for (let i = N - 1; i >= 0; i--) {
        let fila = butacas[i];
        let count = 0;
        let asientos = new Set();

        for (let j = 0; j < N; j++) {

            if (!fila[j].estado) {
                count++;
                asientos.add(fila[j].id);

                // Si encontramos suficientes asientos juntos
                if (count === numAsientos) {
                    // Marcar los asientos como ocupados
                    for (let k = j; k > j - numAsientos; k--) {
                        fila[k].estado = true;
                    }
                    return asientos; 
```

2024-11-14 17:51 UTC, UnirCs requested changes
Se sigue violando la invariante

2024-11-14 22:10 UTC, maibarra0904 commented on Tema_2/Mario_Alberto_Ibarra_Martinez/Cinema/seatingSuggestion.js
> +                    return asientos;
Listo, por favor podría constatar si ya se visualizan los cambios?

2024-11-15 00:12 UTC, UnirCs approved these changes
OK!

2024-11-15 00:12 UTC, merged