Ejercicios Tema 2
UnirCs/DWFS-PER11090-2425 pull request #95
Opened 2024-11-14 02:42 UTC by davidevunir

Implementación de los ejercicios del tema 2, se suben únicamente los archivos javascript.

2024-11-14 17:54 UTC, UnirCs commented on Tema_2/David_Alfredo_Davila_Garzon/Cinema/cinema.js
> +          return new Set(consecutives);
violación de invariante :( 
```java
for (let i = N - 1; i >= 0; i--)
for (let j = 0; j < N; j++)
```
A veces no se cumple

2024-11-14 17:55 UTC, UnirCs requested changes
Se debe refactorizar para no finalizar bucles de forma no lógica

2024-11-15 02:41 UTC, davidevunir commented on Tema_2/David_Alfredo_Davila_Garzon/Cinema/cinema.js
> +          return new Set(consecutives);
He refactorizado el código eliminando los returns dentro de los bucles.
Agradezco su atención.

2024-11-15 02:46 UTC, davidevunir commented
He refactorizado el código eliminando el return dentro del bucle, sin embargo no conozco mucho de github, he colocado un comentario donde se hizo la solicitud de refactorizar y luego le he dado al botón "Resolve conversation" con lo cual ya no veo el comentario sin embargo lo he vuelto a mencionar aquí. Gracias!

2024-11-15 08:50 UTC, UnirCs approved these changes
Ahora está genial, gracias David!

2024-11-15 08:50 UTC, merged