Tarea 2
UnirCs/DWFS-PER11090-2425 pull request #99
Opened 2024-11-14 18:05 UTC by rfalcon97

Tarea 2

2024-11-15 00:13 UTC, UnirCs commented on Tema_2/Ricardo_David_Falcon_Falcon/cinema/cinema.js
> +        return asientosSeleccionados;
como ya comenté en clase no acepto soluciones con breaks, continues o returns dentro de bucles, ya que se viola la invariante

2024-11-15 00:13 UTC, UnirCs requested changes
Necesario refactorizar para no violar invariante

2024-11-17 20:39 UTC, rfalcon97 commented
Se realizó la corrección respectiva

2024-11-17 23:02 UTC, UnirCs approved these changes
OK. Aunque te recomiendo revisar la solución que he puesto en el foro. parece que el ejercicio no esta muy analizado...

2024-11-17 23:03 UTC, merged